export const users = [
    {
        id: crypto.randomUUID(),
        name: "Sophie Laurent",
        email: "sophie.laurent@atelierneuilly.fr",
        emailVerified: true,
        role: "user",
        businessInfo: {
            companyName: "Atelier Neuilly",
            siretNum: "75315985201478",
            productTypes: "Céramique artisanale",
            phone: "0612345679",
            website: "https://atelierneuilly.fr",
            businessDescription: "Créations de céramiques uniques et contemporaines",
        },
    },
    {
        id: crypto.randomUUID(),
        name: "Marc Dubois",
        email: "marc.dubois@maroquinerie-neuilly.fr",
        emailVerified: true,
        role: "user",
        businessInfo: {
            companyName: "Maroquinerie Neuilly",
            siretNum: "85214796301478",
            productTypes: "Maroquinerie de luxe",
            phone: "0698765433",
            website: "https://maroquinerie-neuilly.fr",
            businessDescription: "Création de sacs et accessoires en cuir de luxe",
        },
    },
    {
        id: crypto.randomUUID(),
        name: "Emma Martin",
        email: "emma.martin@bijoux-neuilly.fr",
        emailVerified: true,
        role: "user",
        businessInfo: {
            companyName: "Bijoux Neuilly",
            siretNum: "96325874101478",
            productTypes: "Bijouterie fine",
            phone: "0612345680",
            website: "https://bijoux-neuilly.fr",
            businessDescription: "Création de bijoux contemporains et personnalisés",
        },
    },
    {
        id: crypto.randomUUID(),
        name: "Thomas Petit",
        email: "thomas.petit@meubles-neuilly.fr",
        emailVerified: true,
        role: "user",
        businessInfo: {
            companyName: "Atelier de Menuiserie Neuilly",
            siretNum: "74125896301478",
            productTypes: "Menuiserie sur mesure",
            phone: "0698765434",
            website: "https://meubles-neuilly.fr",
            businessDescription: "Création de meubles sur mesure et rénovation",
        },
    },
    {
        id: crypto.randomUUID(),
        name: "Clara Bernard",
        email: "clara.bernard@couture-neuilly.fr",
        emailVerified: true,
        role: "user",
        businessInfo: {
            companyName: "Atelier de Couture Neuilly",
            siretNum: "85236974101478",
            productTypes: "Couture sur mesure",
            phone: "0612345681",
            website: "https://couture-neuilly.fr",
            businessDescription: "Création de vêtements sur mesure et retouches",
        },
    },
    {
        id: crypto.randomUUID(),
        name: "Lucas Moreau",
        email: "lucas.moreau@verrerie-neuilly.fr",
        emailVerified: true,
        role: "user",
        businessInfo: {
            companyName: "Verrerie d'Art Neuilly",
            siretNum: "96314785201478",
            productTypes: "Verrerie d'art",
            phone: "0698765435",
            website: "https://verrerie-neuilly.fr",
            businessDescription: "Création d'objets en verre soufflé et vitraux",
        },
    },
    {
        id: crypto.randomUUID(),
        name: "Marie Dupont",
        email: "marie.dupont@chocolaterie-neuilly.fr",
        emailVerified: true,
        role: "user",
        businessInfo: {
            companyName: "Chocolaterie Fine Neuilly",
            siretNum: "74185296301478",
            productTypes: "Chocolaterie artisanale",
            phone: "0612345682",
            website: "https://chocolaterie-neuilly.fr",
            businessDescription: "Création de chocolats fins et pralines artisanales",
        },
    },
    {
        id: crypto.randomUUID(),
        name: "Antoine Rousseau",
        email: "antoine.rousseau@horlogerie-neuilly.fr",
        emailVerified: true,
        role: "user",
        businessInfo: {
            companyName: "Atelier d'Horlogerie Neuilly",
            siretNum: "85296374101478",
            productTypes: "Horlogerie fine",
            phone: "0698765436",
            website: "https://horlogerie-neuilly.fr",
            businessDescription: "Restauration et création d'horloges et montres",
        },
    },
    {
        id: crypto.randomUUID(),
        name: "Julie Martin",
        email: "julie.martin@fleuriste-neuilly.fr",
        emailVerified: true,
        role: "user",
        businessInfo: {
            companyName: "Fleuriste Créatif Neuilly",
            siretNum: "96374185201478",
            productTypes: "Art floral",
            phone: "0612345683",
            website: "https://fleuriste-neuilly.fr",
            businessDescription: "Compositions florales artistiques et décoration événementielle",
        },
    },
    {
        id: crypto.randomUUID(),
        name: "Pierre Laurent",
        email: "pierre.laurent@joaillerie-neuilly.fr",
        emailVerified: true,
        role: "user",
        businessInfo: {
            companyName: "Joaillerie Neuilly",
            siretNum: "74196385201478",
            productTypes: "Joaillerie",
            phone: "0698765437",
            website: "https://joaillerie-neuilly.fr",
            businessDescription: "Création de bijoux précieux et sertissage",
        },
    },
    {
        id: crypto.randomUUID(),
        name: "Sophie Dubois",
        email: "sophie.dubois@relaisserie-neuilly.fr",
        emailVerified: true,
        role: "user",
        businessInfo: {
            companyName: "Relais Neuilly",
            siretNum: "85274196301478",
            productTypes: "Relais et tissus",
            phone: "0612345684",
            website: "https://relaisserie-neuilly.fr",
            businessDescription: "Création de tissus d'ameublement et rideaux sur mesure",
        },
    },
    {
        id: crypto.randomUUID(),
        name: "Nicolas Bernard",
        email: "nicolas.bernard@ebenisterie-neuilly.fr",
        emailVerified: true,
        role: "user",
        businessInfo: {
            companyName: "Ébénisterie Neuilly",
            siretNum: "96385274101478",
            productTypes: "Ébénisterie",
            phone: "0698765438",
            website: "https://ebenisterie-neuilly.fr",
            businessDescription: "Restauration et création de meubles en bois précieux",
        },
    },
    {
        id: crypto.randomUUID(),
        name: "Camille Petit",
        email: "camille.petit@tapisserie-neuilly.fr",
        emailVerified: true,
        role: "user",
        businessInfo: {
            companyName: "Tapisserie Neuilly",
            siretNum: "74196385201479",
            productTypes: "Tapisserie",
            phone: "0612345685",
            website: "https://tapisserie-neuilly.fr",
            businessDescription: "Restauration de sièges et création de tissus d'ameublement",
        },
    },
    {
        id: crypto.randomUUID(),
        name: "Léo Martin",
        email: "leo.martin@lutherie-neuilly.fr",
        emailVerified: true,
        role: "user",
        businessInfo: {
            companyName: "Lutherie Neuilly",
            siretNum: "85296374101479",
            productTypes: "Lutherie",
            phone: "0698765439",
            website: "https://lutherie-neuilly.fr",
            businessDescription: "Fabrication et restauration d'instruments à cordes",
        },
    },
    {
        id: crypto.randomUUID(),
        name: "Emma Laurent",
        email: "emma.laurent@encadrement-neuilly.fr",
        emailVerified: true,
        role: "user",
        businessInfo: {
            companyName: "Encadrement Neuilly",
            siretNum: "96374185201479",
            productTypes: "Encadrement d'art",
            phone: "0612345686",
            website: "https://encadrement-neuilly.fr",
            businessDescription: "Encadrement d'œuvres d'art et restauration de cadres",
        },
    },
    {
        id: crypto.randomUUID(),
        name: "Thomas Dubois",
        email: "thomas.dubois@serigraphie-neuilly.fr",
        emailVerified: true,
        role: "user",
        businessInfo: {
            companyName: "Sérigraphie Neuilly",
            siretNum: "74185296301479",
            productTypes: "Sérigraphie",
            phone: "0698765440",
            website: "https://serigraphie-neuilly.fr",
            businessDescription: "Impression sérigraphique artisanale sur textile",
        },
    }
];

export const documents = [
    {
        id: crypto.randomUUID(),
        title: "Guide des bonnes pratiques artisanales",
        description: "Document de référence pour les artisans",
        fileUrl: "https://storage.example.com/documents/guide.pdf",
        fileKey: "guide.pdf",
        fileSize: "2097152", // 2MB
        fileType: "application/pdf",
        uploadedById: users[0].id,
    },
    {
        id: crypto.randomUUID(),
        title: "Catalogue des produits 2025",
        description: "Catalogue complet des produits disponibles",
        fileUrl: "https://storage.example.com/documents/catalogue.pdf",
        fileKey: "catalogue.pdf",
        fileSize: "5242880", // 5MB
        fileType: "application/pdf",
        uploadedById: users[0].id,
    },
];

export const requests = [
    {
        id: crypto.randomUUID(),
        userId: users[0].id,
        content:
            "Je souhaite créer une nouvelle collection de produits artisanaux.",
        status: "en cours" as const,
    },
    {
        id: crypto.randomUUID(),
        userId: users[0].id,
        content:
            "Demande d'ajout de nouveaux types de produits dans le catalogue.",
        status: "validée" as const,
    },
    {
        id: crypto.randomUUID(),
        userId: users[1].id,
        content: "Proposition de partenariat pour une exposition commune.",
        status: "en cours" as const,
    },
    {
        id: crypto.randomUUID(),
        userId: users[1].id,
        content:
            "Demande de modification des informations de mon entreprise.",
        status: "rejetée" as const,
    },
];